name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: sudo apt install libsqlite3-dev

      - name: Setup LLVM
        uses: ZhongRuoyu/setup-llvm@v0
        with:
          llvm-version: 19

      - uses: haskell-actions/setup@v2
        with:
          ghc-version: "9.12.2"
          enable-stack: true

      - name: Build
        run: |
          stack install --stack-yaml stack-release.yaml --system-ghc --local-bin-path ./bin/

      - name: Compress binaries (Unix)
        if: runner.os != 'Windows'
        uses: crazy-max/ghaction-upx@v3
        with:
          version: latest
          files: ./bin/*
          args: -fq

      - name: Package binaries
        run: |
          version="${GITHUB_REF#refs/tags/}"
          cd bin
          tar -czf ../hs-hath-${version}-${{ matrix.os }}.tar.gz *

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hs-hath-${{ matrix.os }}
          path: "hs-hath-*.tar.gz"

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: List assets
        id: asset_names
        run: |
          cd artifacts
          assets=$(ls hs-hath-*.tar.gz | tr '\n' ' ')
          echo "LIST=${assets}" >> $GITHUB_OUTPUT

      - name: Check if pre-release
        id: is_pre_release
        run: |
          version="${GITHUB_REF#refs/tags/}"
          if [[ "${version}" =~ -.*$ ]]; then
            echo "IS_PRERELEASE=true" >> $GITHUB_OUTPUT
          else
            echo "IS_PRERELEASE=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Release
        uses: docker://antonyurchenko/git-release:v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRAFT_RELEASE: "false"
          PRE_RELEASE: ${{ steps.is_pre_release.outputs.IS_PRERELEASE }}
          CHANGELOG_FILE: "CHANGELOG.md"
          ALLOW_EMPTY_CHANGELOG: "false"
          ALLOW_TAG_PREFIX: "true"
        with:
          args: |
            artifacts/${{ steps.asset_names.outputs.LIST }}
